<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class TeacherSeeder extends Seeder
{
    /**
     * Run the database seeds.  
     *
     * @return void
     */
    public function run()
    {
        DB::table('teachers')->insert([
            // Kategori: Struktural
            [
                'name' => 'Tisna Sudrajat, S.Kom., Gr., ACA.',
                'photo' => 'default-user.png',
                'position' => 'Kepala SMK Amaliah 1',
                'subject' => '-',
                'school' => 'Amaliah 1',
                'category' => 'Struktural',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Dr. Gugun Gunadi, S.Pd.I., M.Pd.',
                'photo' => 'default-user.png',
                'position' => 'Kepala SMK Amaliah 2',
                'subject' => '-',
                'school' => 'Amaliah 2',
                'category' => 'Struktural',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Rd. Hendriawan Tansyah, S.T., Gr',
                'photo' => 'default-user.png',
                'position' => 'Waka. Kurikulum SMK Amaliah 1',
                'subject' => 'Produktif PPLG',
                'school' => 'Amaliah 1',
                'category' => 'Struktural',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Isma Tri Pamungkas, S.Pd., Gr',
                'photo' => 'default-user.png',
                'position' => 'Waka. Hubin SMK Amaliah 1',
                'subject' => 'Bahasa Inggris',
                'school' => 'Amaliah 1',
                'category' => 'Struktural',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Amirudin Muslim, S.Pd.I., MM., Gr',
                'photo' => 'default-user.png',
                'position' => 'Waka. Kesiswaan SMK Amaliah 1',
                'subject' => 'PAI',
                'school' => 'Amaliah 1',
                'category' => 'Struktural',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Abdul Azis Sudrajat, S.Kom',
                'photo' => 'default-user.png',
                'position' => 'Waka. Sarpras SMK Amaliah 1',
                'subject' => 'Produktif TJKT',
                'school' => 'Amaliah 1',
                'category' => 'Struktural',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Siti Wadiah, SE.I., Gr',
                'photo' => 'default-user.png',
                'position' => 'Waka. Kurikulum SMK Amaliah 2',
                'subject' => 'Produktif MP',
                'school' => 'Amaliah 2',
                'category' => 'Struktural',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Yulianti Ramadhan, S.Pd., Gr',
                'photo' => 'default-user.png',
                'position' => 'Waka. Hubin SMK Amaliah 2',
                'subject' => 'Bahasa Inggris',
                'school' => 'Amaliah 2',
                'category' => 'Struktural',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Gilang Gumilar, SE.I., Gr',
                'photo' => 'default-user.png',
                'position' => 'Waka. Kesiswaan SMK Amaliah 2',
                'subject' => 'Produktif LPS',
                'school' => 'Amaliah 2',
                'category' => 'Struktural',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Heni Nuraeni, SE',
                'photo' => 'default-user.png',
                'position' => 'Waka. Sarpras SMK Amaliah 2',
                'subject' => 'Produktif MP',
                'school' => 'Amaliah 2',
                'category' => 'Struktural',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Yeni Latifah, S.Kom., Gr',
                'photo' => 'default-user.png',
                'position' => 'Kepala TU SMK Amaliah 1&2',
                'subject' => 'Informatika',
                'school' => 'Amaliah 1 & 2',
                'category' => 'Struktural',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Selvia Safitri, S.I.Kom',
                'photo' => 'default-user.png',
                'position' => 'Koordinator BKK SMK Amaliah 1&2',
                'subject' => 'Produktif MP',
                'school' => 'Amaliah 1 & 2',
                'category' => 'Struktural',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // Kategori: Produktif
            [
                'name' => 'Septiyandi Utama, A.Md',
                'photo' => 'default-user.png',
                'position' => 'Kepala Kompetensi TJKT',
                'subject' => 'Produktif TJKT',
                'school' => 'Amaliah 1 & 2',
                'category' => 'Produktif',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Muhamad Rendi N, S.I.Kom',
                'photo' => 'default-user.png',
                'position' => 'Kepala Kompetensi AN',
                'subject' => 'Produktif AN',
                'school' => 'Amaliah 1 & 2',
                'category' => 'Produktif',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Selvia Prihastyani, S.Kom., Gr',
                'photo' => 'default-user.png',
                'position' => 'Kepala Kompetensi PPLG',
                'subject' => 'Produktif PPLG',
                'school' => 'Amaliah 1 & 2',
                'category' => 'Produktif',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Dwi Handayani, S.Kom., Gr',
                'photo' => 'default-user.png',
                'position' => 'Kepala Kompetensi MP',
                'subject' => 'Produktif MP',
                'school' => 'Amaliah 1 & 2',
                'category' => 'Produktif',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Aidina Barek Hoda, SE',
                'photo' => 'default-user.png',
                'position' => 'Kepala Kompetensi LPS',
                'subject' => 'Produktif LPS',
                'school' => 'Amaliah 1 & 2',
                'category' => 'Produktif',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Tri Ekawati, S.Pd., Gr',
                'photo' => 'default-user.png',
                'position' => 'Kepala Kompetensi DPB',
                'subject' => 'Produktif DPB',
                'school' => 'Amaliah 1 & 2',
                'category' => 'Produktif',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Mila Karmila, SE',
                'photo' => 'default-user.png',
                'position' => 'Kepala Kompetensi AKL',
                'subject' => 'Produktif AKL',
                'school' => 'Amaliah 1 & 2',
                'category' => 'Produktif',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Reni Oktaviani, SE',
                'photo' => 'default-user.png',
                'position' => 'Kepala Kompetensi BR',
                'subject' => 'Produktif BR',
                'school' => 'Amaliah 1 & 2',
                'category' => 'Produktif',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Mudin, S.I.Kom',
                'photo' => 'default-user.png',
                'position' => 'Kepala Kompetensi DKV',
                'subject' => 'Produktif DKV',
                'school' => 'Amaliah 1 & 2',
                'category' => 'Produktif',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Rahmi Putri Handayani, SE.I., Gr',
                'photo' => 'default-user.png',
                'position' => 'Koordinator Keagamaan',
                'subject' => 'Produktif LPS',
                'school' => 'Amaliah 2',
                'category' => 'Produktif',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Muhammad Romdhoni, S.I.Kom',
                'photo' => 'default-user.png',
                'position' => 'Pembina Osis',
                'subject' => 'Produktif AN',
                'school' => 'Amaliah 1',
                'category' => 'Produktif',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Iqbal Firdaus, A.Md',
                'photo' => 'default-user.png',
                'position' => 'Guru',
                'subject' => 'Produktif TJKT',
                'school' => 'Amaliah 1 & 2',
                'category' => 'Produktif',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Aviani Sofiansyah',
                'photo' => 'default-user.png',
                'position' => 'Guru',
                'subject' => 'Produktif PPLG',
                'school' => 'Amaliah 1 & 2',
                'category' => 'Produktif',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Deden Zaenudin, S.Pd',
                'photo' => 'default-user.png',
                'position' => 'Guru',
                'subject' => 'Produktif AN',
                'school' => 'Amaliah 1 & 2',
                'category' => 'Produktif',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Muhamad Subhan Hidayat',
                'photo' => 'default-user.png',
                'position' => 'Guru',
                'subject' => 'Produktif TJKT',
                'school' => 'Amaliah 1 & 2',
                'category' => 'Produktif',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Rizky Septiyadi W, S.Kom',
                'photo' => 'default-user.png',
                'position' => 'Guru',
                'subject' => 'Produktif TJKT',
                'school' => 'Amaliah 1 & 2',
                'category' => 'Produktif',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Intan Sri Mulyani, S.Kom',
                'photo' => 'default-user.png',
                'position' => 'Guru',
                'subject' => 'Produktif PPLG',
                'school' => 'Amaliah 1 & 2',
                'category' => 'Produktif',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Siti Nurafifah, S.Pd',
                'photo' => 'default-user.png',
                'position' => 'Guru',
                'subject' => 'Produktif DPB',
                'school' => 'Amaliah 1 & 2',
                'category' => 'Produktif',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Rismayanti, SE',
                'photo' => 'default-user.png',
                'position' => 'Guru',
                'subject' => 'Produktif MP',
                'school' => 'Amaliah 1 & 2',
                'category' => 'Produktif',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Annisa Riani, SE',
                'photo' => 'default-user.png',
                'position' => 'Guru',
                'subject' => 'Produktif MP',
                'school' => 'Amaliah 1 & 2',
                'category' => 'Produktif',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Siti Hertiwi Khasanah, S.M',
                'photo' => 'default-user.png',
                'position' => 'Guru',
                'subject' => 'Produktif BR, DPB, MP',
                'school' => 'Amaliah 1 & 2',
                'category' => 'Produktif',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Siti Nur Alfina',
                'photo' => 'default-user.png',
                'position' => 'Guru',
                'subject' => 'Produktif DPB',
                'school' => 'Amaliah 1 & 2',
                'category' => 'Produktif',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Sylvia Rachmawati, S.M',
                'photo' => 'default-user.png',
                'position' => 'Guru',
                'subject' => 'Produktif MP',
                'school' => 'Amaliah 1 & 2',
                'category' => 'Produktif',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Dede Jaenudin, S. E.',
                'photo' => 'default-user.png',
                'position' => 'Guru',
                'subject' => 'Produktif AK',
                'school' => 'Amaliah 1 & 2',
                'category' => 'Produktif',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Mulyana, S.E',
                'photo' => 'default-user.png',
                'position' => 'Guru',
                'subject' => 'Produktif AK',
                'school' => 'Amaliah 1 & 2',
                'category' => 'Produktif',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Nurul Febryanti Rachmanissa, SM',
                'photo' => 'default-user.png',
                'position' => 'Guru',
                'subject' => 'Produktif MP',
                'school' => 'Amaliah 1 & 2',
                'category' => 'Produktif',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Zahra Azkia Ibrahim, SM',
                'photo' => 'default-user.png',
                'position' => 'Guru',
                'subject' => 'Produktif AK',
                'school' => 'Amaliah 1 & 2',
                'category' => 'Produktif',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Miftahul Khoir, M. E.',
                'photo' => 'default-user.png',
                'position' => 'Guru',
                'subject' => 'Produktif TJKT',
                'school' => 'Amaliah 1 & 2',
                'category' => 'Produktif',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Tia Agustiani, S.Kom',
                'photo' => 'default-user.png',
                'position' => 'Guru',
                'subject' => 'Produktif AN',
                'school' => 'Amaliah 1 & 2',
                'category' => 'Produktif',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Laila Azra, SE',
                'photo' => 'default-user.png',
                'position' => 'Guru',
                'subject' => 'PKK & Produktif MP',
                'school' => 'Amaliah 1 & 2',
                'category' => 'Produktif',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            
            // Kategori: Adaptif
            [
                'name' => 'Ami Listiami, SP.',
                'photo' => 'default-user.png',
                'position' => 'Koordinator BK',
                'subject' => 'IPAS & BK',
                'school' => 'Amaliah 1',
                'category' => 'Adaptif',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Siti Sarah Monika, S.Pd',
                'photo' => 'default-user.png',
                'position' => 'Pembina Osis',
                'subject' => 'Bahasa Inggris',
                'school' => 'Amaliah 2',
                'category' => 'Adaptif',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Mimi Sumiati, S.Pd., Gr',
                'photo' => 'default-user.png',
                'position' => 'Guru',
                'subject' => 'B. Inggris & TOEIC',
                'school' => 'Amaliah 1 & 2',
                'category' => 'Adaptif',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Hadi Pasito, S.Si',
                'photo' => 'default-user.png',
                'position' => 'Guru',
                'subject' => 'IPAS',
                'school' => 'Amaliah 1 & 2',
                'category' => 'Adaptif',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Else As Syavira, S.Mat',
                'photo' => 'default-user.png',
                'position' => 'Guru',
                'subject' => 'Matematika',
                'school' => 'Amaliah 1 & 2',
                'category' => 'Adaptif',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Indra Delta, SH., ΜΗ',
                'photo' => 'default-user.png',
                'position' => 'Guru',
                'subject' => 'IPAS',
                'school' => 'Amaliah 1 & 2',
                'category' => 'Adaptif',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Annisa, S.Pd',
                'photo' => 'default-user.png',
                'position' => 'Guru',
                'subject' => 'B. Inggris',
                'school' => 'Amaliah 1 & 2',
                'category' => 'Adaptif',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Putriani Nur Khotimah',
                'photo' => 'default-user.png',
                'position' => 'Guru',
                'subject' => 'Matematika',
                'school' => 'Amaliah 1 & 2',
                'category' => 'Adaptif',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Kharunisa, S.Psi',
                'photo' => 'default-user.png',
                'position' => 'Guru',
                'subject' => 'BK',
                'school' => 'Amaliah 1 & 2',
                'category' => 'Adaptif',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // Kategori: Normatif
            [
                'name' => 'Ernawati, S.PD., Gr',
                'photo' => 'default-user.png',
                'position' => 'Guru',
                'subject' => 'B. Indonesia',
                'school' => 'Amaliah 1 & 2',
                'category' => 'Normatif',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Septa Sopiatun, S.Pd., Gr',
                'photo' => 'default-user.png',
                'position' => 'Guru',
                'subject' => 'Seni Budaya',
                'school' => 'Amaliah 1 & 2',
                'category' => 'Normatif',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Ana Luciana, S.Pd',
                'photo' => 'default-user.png',
                'position' => 'Guru',
                'subject' => 'B. Indonesia',
                'school' => 'Amaliah 1 & 2',
                'category' => 'Normatif',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Guna Tata Pijana, S.Sos., Gr',
                'photo' => 'default-user.png',
                'position' => 'Guru',
                'subject' => 'Pendidikan Pancasila',
                'school' => 'Amaliah 1 & 2',
                'category' => 'Normatif',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Wenny Isnawati, S.Pd., Gr',
                'photo' => 'default-user.png',
                'position' => 'Guru',
                'subject' => 'B. Indonesia',
                'school' => 'Amaliah 1 & 2',
                'category' => 'Normatif',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Siti Nurjanah Nasution, S.Pd',
                'photo' => 'default-user.png',
                'position' => 'Guru',
                'subject' => 'PJOK',
                'school' => 'Amaliah 1 & 2',
                'category' => 'Normatif',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Syahrul Ramdoni, S.I.Kom',
                'photo' => 'default-user.png',
                'position' => 'Guru',
                'subject' => 'PKK',
                'school' => 'Amaliah 1 & 2',
                'category' => 'Normatif',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Muhammad Sayuti, SH',
                'photo' => 'default-user.png',
                'position' => 'Guru',
                'subject' => 'PKN',
                'school' => 'Amaliah 1 & 2',
                'category' => 'Normatif',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Muhammad Mukhlisin, S.Pd.I',
                'photo' => 'default-user.png',
                'position' => 'Guru',
                'subject' => 'PAI',
                'school' => 'Amaliah 1 & 2',
                'category' => 'Normatif',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Yogi Ahmad, SE',
                'photo' => 'default-user.png',
                'position' => 'Guru',
                'subject' => 'PJOK',
                'school' => 'Amaliah 1 & 2',
                'category' => 'Normatif',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Oce Komarudin, S.Ag., MM',
                'photo' => 'default-user.png',
                'position' => 'Guru',
                'subject' => 'PAI & Akhlak Tauhid',
                'school' => 'Amaliah 1 & 2',
                'category' => 'Normatif',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Rani Oktaviani, S.Pd',
                'photo' => 'default-user.png',
                'position' => 'Guru',
                'subject' => 'Akhlak Tauhid',
                'school' => 'Amaliah 1 & 2',
                'category' => 'Normatif',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Neylanur Maulidiyah, S.Pd',
                'photo' => 'default-user.png',
                'position' => 'Guru',
                'subject' => 'B. Jepang',
                'school' => 'Amaliah 1 & 2',
                'category' => 'Normatif',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Tuti Susilawati, S.Pd., Gr',
                'photo' => 'default-user.png',
                'position' => 'Guru',
                'subject' => 'PKN & Sejarah',
                'school' => 'Amaliah 1 & 2',
                'category' => 'Normatif',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Siti Nuranisah, S.Pd',
                'photo' => 'default-user.png',
                'position' => 'Guru',
                'subject' => 'B. Indonesia & Sunda',
                'school' => 'Amaliah 1 & 2',
                'category' => 'Normatif',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Akwal Syahril, SH',
                'photo' => 'default-user.png',
                'position' => 'Guru',
                'subject' => 'PAI',
                'school' => 'Amaliah 1 & 2',
                'category' => 'Normatif',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Riris Mawrisal Jannah, S.PD',
                'photo' => 'default-user.png',
                'position' => 'Guru',
                'subject' => 'B. Arab & Akhlak Tauhid',
                'school' => 'Amaliah 1 & 2',
                'category' => 'Normatif',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Niar Handayani, SS',
                'photo' => 'default-user.png',
                'position' => 'Guru',
                'subject' => 'B. Jepang',
                'school' => 'Amaliah 1 & 2',
                'category' => 'Normatif',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Siti Amaliah, S.PD',
                'photo' => 'default-user.png',
                'position' => 'Guru',
                'subject' => 'PKK',
                'school' => 'Amaliah 1 & 2',
                'category' => 'Normatif',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Siti Sahidah, S.Pd',
                'photo' => 'default-user.png',
                'position' => 'Guru',
                'subject' => 'B. Arab',
                'school' => 'Amaliah 1 & 2',
                'category' => 'Normatif',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Muhammad Abdul Malik',
                'photo' => 'default-user.png',
                'position' => 'Guru',
                'subject' => 'Akhlak Tauhid',
                'school' => 'Amaliah 1 & 2',
                'category' => 'Normatif',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

        ]);
    }
}